version: '3.6'
services:

  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: directory_user
      POSTGRES_DB: directory

  dirgraph:
    build:
      context: ./build
      dockerfile: local/Dockerfile
    depends_on:
      - postgres
    environment:
      ENV: local
      PGPASSWORD: iamaninsecurepassword
      PGUSER: directory_user
      PGDATABASE: directory
      PGHOST: postgres
    ports:
      - 4023:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
