---
apiVersion: v1
kind: ConfigMap
metadata:
  name: directory-graph-postgres-config
  labels:
    app: directory-graph-postgres
data:
  POSTGRES_DB: directory-graph
  POSTGRES_USER: directory-graph_app_rw
  POSTGRES_PASSWORD: D0BF56B00DA62700941259C30607C39D

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: ebs
    app: directory-graph-postgres
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres-data"


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: directory-graph-postgres
spec:
  storageClassName: postgres-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: directory-graph-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: directory-graph-postgres
    spec:
      containers:
        - name: directory-graph-postgres
          image: postgres:10.4
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: directory-graph-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: directory-graph-postgres
      volumes:
        - name: directory-graph-postgres
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: directory-graph-postgres
  labels:
    app: directory-graph-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: directory-graph-postgres
